### ISSUE TITLE
Create a semver tag

### ISSUE THREAD

**Issue by ajb** [gbirke/Sanitize.js#13]
Hey Gabriel, 

It would be super helpful to us bower users if you could create a semver tag in this repository. `1.0.0` will do just fine :)

Thanks in advance!

-- Adam

**Comment by walter** [comment]
+1

I use ember-cli and its add-on system and minutebase has helpfully packaged up Sanitize.js into the ember-sanitize add-on.

Unfortunately/fortunately ember-cli has added strict dependency checking to ember-cli by default. This is good for the general health of my project and I'm loath to turn it off, but ember-sanitize fails because of the sanitize.js bower package lack of semver.

I would really like to take advantage of Sanitize.js as it seems perfect for what I want (thank you for writing it!), but turning off dependency checking seems too big of a trade-off to get it.

@gbirke do you have objections to semver? Is there anything we can do to help resolve this situation?

Thanks again for your hard work!

**Comment by gbirke** [comment]
Hi,

I have created a tag. Is this ok?

**Comment by walter** [comment]
@gbirke that did the trick! Thanks!
